import { TreinoType, DietaType, Alimento, Player } from "@/components/general/types";

export interface MealType {
  id: string;
  name: "Café da manhã" | "Almoço" | "Lanche" | "Janta" | "Outros";
  time?: string;
  alimentos: Alimento[];
}

export interface DietaWithMealsType {
  id: number;
  name: string;
  description?: string;
  dailyCalorieGoal?: number;
  dailyProteinGoal?: number;
  dailyCarbGoal?: number;
  dailyFatGoal?: number;
  waterGoal?: number;
  meals: MealType[];
}


export const getMockFriends = (): Player[] => [
  {
    id_player: 2,
    height: 175,
    weight: 78,
    weeklyTargetDays: 5,
    weeklyStreak: 8,
    lastWeekOfYear: 43,
    currentWeekTrainedDays: 4,
    workouts: [],
    user: {
      id_user: 2,
      username: "Mariana Costa",
      password: "senha",
      email: "mariana.costa@email.com",
    },
    activities: [],
  },
  {
    id_player: 3,
    height: 182,
    weight: 92,
    weeklyTargetDays: 4,
    weeklyStreak: 12,
    lastWeekOfYear: 43,
    currentWeekTrainedDays: 4,
    workouts: [],
    user: {
      id_user: 3,
      username: "Rafael Oliveira",
      password: "senha",
      email: "rafael.oliveira@email.com",
    },
    activities: [],
  },
  {
    id_player: 4,
    height: 168,
    weight: 65,
    weeklyTargetDays: 3,
    weeklyStreak: 3,
    lastWeekOfYear: 43,
    currentWeekTrainedDays: 2,
    workouts: [],
    user: {
      id_user: 4,
      username: "Ana Paula Santos",
      password: "senha",
      email: "ana.santos@email.com",
    },
    activities: [],
  },
  {
    id_player: 5,
    height: 179,
    weight: 88,
    weeklyTargetDays: 5,
    weeklyStreak: 5,
    lastWeekOfYear: 43,
    currentWeekTrainedDays: 3,
    workouts: [],
    user: {
      id_user: 5,
      username: "Bruno Ferreira",
      password: "senha",
      email: "bruno.ferreira@email.com",
    },
    activities: [],
  },
  {
    id_player: 6,
    height: 171,
    weight: 70,
    weeklyTargetDays: 4,
    weeklyStreak: 1,
    lastWeekOfYear: 43,
    currentWeekTrainedDays: 1,
    workouts: [],
    user: {
      id_user: 6,
      username: "Camila Rodrigues",
      password: "senha",
      email: "camila.rodrigues@email.com",
    },
    activities: [],
  },
];


export const getMockWorkouts = (): TreinoType[] => [
  {
    id: 1,
    name: "Treino de Peito e Tríceps",
    description: "Foco em desenvolvimento da musculatura peitoral e tríceps com exercícios compostos",
    totalExercises: 6,
    totalSeries: 18,
    complete: false,
    exercises: [
      {
        id: 1,
        name: "Supino Reto com Barra",
        muscles: "Peitoral Maior, Tríceps, Deltóide Anterior",
        repeticoes: 10,
        series: 4,
        complete: false,
      },
      {
        id: 2,
        name: "Supino Inclinado com Halteres",
        muscles: "Peitoral Superior, Deltóide Anterior",
        repeticoes: 12,
        series: 3,
        complete: false,
      },
      {
        id: 3,
        name: "Crucifixo na Polia",
        muscles: "Peitoral Maior",
        repeticoes: 15,
        series: 3,
        complete: false,
      },
      {
        id: 4,
        name: "Tríceps Testa com Barra W",
        muscles: "Tríceps",
        repeticoes: 12,
        series: 3,
        complete: false,
      },
      {
        id: 5,
        name: "Tríceps na Polia",
        muscles: "Tríceps",
        repeticoes: 15,
        series: 3,
        complete: false,
      },
      {
        id: 6,
        name: "Mergulho no Banco",
        muscles: "Tríceps, Peitoral Inferior",
        repeticoes: 12,
        series: 2,
        complete: false,
      },
    ],
  },
  {
    id: 2,
    name: "Treino de Costas e Bíceps",
    description: "Desenvolvimento completo da musculatura dorsal e bíceps",
    totalExercises: 6,
    totalSeries: 19,
    complete: true,
    exercises: [
      {
        id: 7,
        name: "Barra Fixa",
        muscles: "Grande Dorsal, Bíceps",
        repeticoes: 8,
        series: 4,
        complete: true,
      },
      {
        id: 8,
        name: "Remada Curvada com Barra",
        muscles: "Grande Dorsal, Trapézio",
        repeticoes: 10,
        series: 4,
        complete: true,
      },
      {
        id: 9,
        name: "Puxada Frontal",
        muscles: "Grande Dorsal",
        repeticoes: 12,
        series: 3,
        complete: true,
      },
      {
        id: 10,
        name: "Remada na Máquina",
        muscles: "Grande Dorsal, Trapézio",
        repeticoes: 12,
        series: 3,
        complete: true,
      },
      {
        id: 11,
        name: "Rosca Direta com Barra",
        muscles: "Bíceps",
        repeticoes: 10,
        series: 3,
        complete: true,
      },
      {
        id: 12,
        name: "Rosca Martelo com Halteres",
        muscles: "Bíceps, Braquial",
        repeticoes: 12,
        series: 2,
        complete: true,
      },
    ],
  },
  {
    id: 3,
    name: "Treino de Pernas Completo",
    description: "Treino intenso para quadríceps, posterior e glúteos",
    totalExercises: 5,
    totalSeries: 16,
    complete: false,
    exercises: [
      {
        id: 13,
        name: "Agachamento Livre",
        muscles: "Quadríceps, Glúteos, Posterior",
        repeticoes: 8,
        series: 4,
        complete: false,
      },
      {
        id: 14,
        name: "Leg Press 45°",
        muscles: "Quadríceps, Glúteos",
        repeticoes: 12,
        series: 4,
        complete: false,
      },
      {
        id: 15,
        name: "Mesa Flexora",
        muscles: "Posterior de Coxa",
        repeticoes: 12,
        series: 3,
        complete: false,
      },
      {
        id: 16,
        name: "Cadeira Extensora",
        muscles: "Quadríceps",
        repeticoes: 15,
        series: 3,
        complete: false,
      },
      {
        id: 17,
        name: "Panturrilha no Smith",
        muscles: "Panturrilha",
        repeticoes: 20,
        series: 2,
        complete: false,
      },
    ],
  },
  {
    id: 4,
    name: "Treino de Ombros e Abdômen",
    description: "Fortalecimento dos deltóides e core",
    totalExercises: 5,
    totalSeries: 15,
    complete: false,
    exercises: [
      {
        id: 18,
        name: "Desenvolvimento com Barra",
        muscles: "Deltóide, Trapézio",
        repeticoes: 10,
        series: 4,
        complete: false,
      },
      {
        id: 19,
        name: "Elevação Lateral com Halteres",
        muscles: "Deltóide Medial",
        repeticoes: 12,
        series: 3,
        complete: false,
      },
      {
        id: 20,
        name: "Elevação Frontal com Disco",
        muscles: "Deltóide Anterior",
        repeticoes: 12,
        series: 3,
        complete: false,
      },
      {
        id: 21,
        name: "Crucifixo Inverso na Polia",
        muscles: "Deltóide Posterior",
        repeticoes: 15,
        series: 3,
        complete: false,
      },
      {
        id: 22,
        name: "Abdominal na Prancha",
        muscles: "Abdômen, Core",
        repeticoes: 30,
        series: 2,
        complete: false,
      },
    ],
  },
];

export const getMockDietsWithMeals = (): DietaWithMealsType[] => [
  {
    id: 1,
    name: "Dieta Ganho de Massa",
    description: "Dieta hipercalórica para hipertrofia muscular",
    dailyCalorieGoal: 3200,
    dailyProteinGoal: 180,
    dailyCarbGoal: 400,
    dailyFatGoal: 80,
    waterGoal: 3000,
    meals: [
      {
        id: "breakfast-1",
        name: "Café da manhã",
        time: "07:00",
        alimentos: [
          {
            id: 1,
            name: "Ovos Mexidos (3 unidades)",
            calories: 290,
            fats: 16,
            carbs: 2,
            fibers: 0,
            sodium: 186,
            proteins: 20,
            acucars: { id: 1, acucarTotal: 2, acucarAdicionado: 0 },
            gorduras: {
              id: 1,
              gorduraTrans: 0,
              gordurasMonosaturadas: 6.2,
              gordurasPoliinsaturadas: 2.1,
              gordurasSaturadas: 5,
            },
          },
          {
            id: 2,
            name: "Aveia com Banana",
            calories: 180,
            fats: 3,
            carbs: 32,
            fibers: 4,
            sodium: 5,
            proteins: 6,
            acucars: { id: 2, acucarTotal: 8, acucarAdicionado: 0 },
            gorduras: {
              id: 2,
              gorduraTrans: 0,
              gordurasMonosaturadas: 1,
              gordurasPoliinsaturadas: 1,
              gordurasSaturadas: 0.5,
            },
          },
        ],
      },
      {
        id: "lunch-1",
        name: "Almoço",
        time: "12:30",
        alimentos: [
          {
            id: 4,
            name: "Peito de Frango Grelhado (200g)",
            calories: 330,
            fats: 7.2,
            carbs: 0,
            fibers: 0,
            sodium: 148,
            proteins: 62,
            acucars: { id: 4, acucarTotal: 0, acucarAdicionado: 0 },
            gorduras: {
              id: 4,
              gorduraTrans: 0,
              gordurasMonosaturadas: 2.4,
              gordurasPoliinsaturadas: 1.6,
              gordurasSaturadas: 2,
            },
          },
          {
            id: 5,
            name: "Arroz Integral (150g)",
            calories: 167,
            fats: 1.4,
            carbs: 35,
            fibers: 2.7,
            sodium: 8,
            proteins: 3.9,
            acucars: { id: 5, acucarTotal: 0.6, acucarAdicionado: 0 },
            gorduras: {
              id: 5,
              gorduraTrans: 0,
              gordurasMonosaturadas: 0.5,
              gordurasPoliinsaturadas: 0.5,
              gordurasSaturadas: 0.3,
            },
          },
        ],
      },
      {
        id: "snack-1",
        name: "Lanche",
        time: "16:00",
        alimentos: [
          {
            id: 8,
            name: "Whey Protein (30g)",
            calories: 120,
            fats: 1.5,
            carbs: 3,
            fibers: 0,
            sodium: 50,
            proteins: 24,
            acucars: { id: 8, acucarTotal: 2, acucarAdicionado: 0 },
            gorduras: {
              id: 8,
              gorduraTrans: 0,
              gordurasMonosaturadas: 0.5,
              gordurasPoliinsaturadas: 0.3,
              gordurasSaturadas: 0.8,
            },
          },
        ],
      },
      {
        id: "dinner-1",
        name: "Janta",
        time: "19:30",
        alimentos: [
          {
            id: 11,
            name: "Salmão Grelhado (150g)",
            calories: 309,
            fats: 18,
            carbs: 0,
            fibers: 0,
            sodium: 89,
            proteins: 33,
            acucars: { id: 11, acucarTotal: 0, acucarAdicionado: 0 },
            gorduras: {
              id: 11,
              gorduraTrans: 0,
              gordurasMonosaturadas: 6.8,
              gordurasPoliinsaturadas: 6.3,
              gordurasSaturadas: 3.8,
            },
          },
        ],
      },
      {
        id: "other-1",
        name: "Outros",
        alimentos: [],
      },
    ],
  },
  {
    id: 2,
    name: "Dieta Low Carb",
    description: "Baixo carboidrato para definição",
    dailyCalorieGoal: 1800,
    dailyProteinGoal: 140,
    dailyCarbGoal: 80,
    dailyFatGoal: 100,
    waterGoal: 2500,
    meals: [
      {
        id: "breakfast-2",
        name: "Café da manhã",
        time: "07:30",
        alimentos: [
          {
            id: 15,
            name: "Omelete (3 ovos + queijo)",
            calories: 320,
            fats: 24,
            carbs: 3,
            fibers: 0,
            sodium: 450,
            proteins: 24,
            acucars: { id: 15, acucarTotal: 2, acucarAdicionado: 0 },
            gorduras: {
              id: 15,
              gorduraTrans: 0,
              gordurasMonosaturadas: 9,
              gordurasPoliinsaturadas: 3,
              gordurasSaturadas: 10,
            },
          },
        ],
      },
      {
        id: "lunch-2",
        name: "Almoço",
        time: "12:00",
        alimentos: [
          {
            id: 17,
            name: "Carne Vermelha Magra (200g)",
            calories: 290,
            fats: 12,
            carbs: 0,
            fibers: 0,
            sodium: 75,
            proteins: 44,
            acucars: { id: 17, acucarTotal: 0, acucarAdicionado: 0 },
            gorduras: {
              id: 17,
              gorduraTrans: 0,
              gordurasMonosaturadas: 5,
              gordurasPoliinsaturadas: 0.5,
              gordurasSaturadas: 5,
            },
          },
        ],
      },
      {
        id: "snack-2",
        name: "Lanche",
        time: "15:30",
        alimentos: [
          {
            id: 19,
            name: "Iogurte Grego Natural (150g)",
            calories: 100,
            fats: 5,
            carbs: 6,
            fibers: 0,
            sodium: 50,
            proteins: 9,
            acucars: { id: 19, acucarTotal: 5, acucarAdicionado: 0 },
            gorduras: {
              id: 19,
              gorduraTrans: 0,
              gordurasMonosaturadas: 1.5,
              gordurasPoliinsaturadas: 0.2,
              gordurasSaturadas: 3,
            },
          },
        ],
      },
      {
        id: "dinner-2",
        name: "Janta",
        time: "19:00",
        alimentos: [
          {
            id: 20,
            name: "Frango com Legumes",
            calories: 250,
            fats: 8,
            carbs: 12,
            fibers: 4,
            sodium: 200,
            proteins: 35,
            acucars: { id: 20, acucarTotal: 6, acucarAdicionado: 0 },
            gorduras: {
              id: 20,
              gorduraTrans: 0,
              gordurasMonosaturadas: 3,
              gordurasPoliinsaturadas: 2,
              gordurasSaturadas: 2,
            },
          },
        ],
      },
      {
        id: "other-2",
        name: "Outros",
        alimentos: [],
      },
    ],
  },
];


export const getMockDiets = (): DietaType[] => {
  const dietsWithMeals = getMockDietsWithMeals();
  
  return dietsWithMeals.map(diet => ({
    id: diet.id,
    name: diet.name,
    alimentos: diet.meals.flatMap(meal => meal.alimentos),
  }));
};