import { TreinoType, DietaType, Alimento, Player } from "@/components/general/types";

// Mock friends data with Brazilian Portuguese names
export const getMockFriends = (): Player[] => [
  {
    id_player: 2,
    height: 175,
    weight: 78,
    weeklyTargetDays: 5,
    weeklyStreak: 8,
    lastWeekOfYear: 43,
    currentWeekTrainedDays: 4,
    workouts: [],
    user: {
      id_user: 2,
      username: "Mariana Costa",
      password: "senha",
      email: "mariana.costa@email.com",
    },
    activities: [],
  },
  {
    id_player: 3,
    height: 182,
    weight: 92,
    weeklyTargetDays: 4,
    weeklyStreak: 12,
    lastWeekOfYear: 43,
    currentWeekTrainedDays: 4,
    workouts: [],
    user: {
      id_user: 3,
      username: "Rafael Oliveira",
      password: "senha",
      email: "rafael.oliveira@email.com",
    },
    activities: [],
  },
  {
    id_player: 4,
    height: 168,
    weight: 65,
    weeklyTargetDays: 3,
    weeklyStreak: 3,
    lastWeekOfYear: 43,
    currentWeekTrainedDays: 2,
    workouts: [],
    user: {
      id_user: 4,
      username: "Ana Paula Santos",
      password: "senha",
      email: "ana.santos@email.com",
    },
    activities: [],
  },
  {
    id_player: 5,
    height: 179,
    weight: 88,
    weeklyTargetDays: 5,
    weeklyStreak: 5,
    lastWeekOfYear: 43,
    currentWeekTrainedDays: 3,
    workouts: [],
    user: {
      id_user: 5,
      username: "Bruno Ferreira",
      password: "senha",
      email: "bruno.ferreira@email.com",
    },
    activities: [],
  },
  {
    id_player: 6,
    height: 171,
    weight: 70,
    weeklyTargetDays: 4,
    weeklyStreak: 1,
    lastWeekOfYear: 43,
    currentWeekTrainedDays: 1,
    workouts: [],
    user: {
      id_user: 6,
      username: "Camila Rodrigues",
      password: "senha",
      email: "camila.rodrigues@email.com",
    },
    activities: [],
  },
];

// Mock workout data with Brazilian Portuguese names
export const getMockWorkouts = (): TreinoType[] => [
  {
    id: 1,
    name: "Treino de Peito e Tríceps",
    description:
      "Foco em desenvolvimento da musculatura peitoral e tríceps com exercícios compostos",
    totalExercises: 6,
    totalSeries: 18,
    complete: false,
    exercises: [
      {
        id: 1,
        name: "Supino Reto com Barra",
        muscles: "Peitoral Maior, Tríceps, Deltóide Anterior",
        repeticoes: 10,
        series: 4,
        complete: false,
      },
      {
        id: 2,
        name: "Supino Inclinado com Halteres",
        muscles: "Peitoral Superior, Deltóide Anterior",
        repeticoes: 12,
        series: 3,
        complete: false,
      },
      {
        id: 3,
        name: "Crucifixo na Polia",
        muscles: "Peitoral Maior",
        repeticoes: 15,
        series: 3,
        complete: false,
      },
      {
        id: 4,
        name: "Tríceps Testa com Barra W",
        muscles: "Tríceps",
        repeticoes: 12,
        series: 3,
        complete: false,
      },
      {
        id: 5,
        name: "Tríceps na Polia",
        muscles: "Tríceps",
        repeticoes: 15,
        series: 3,
        complete: false,
      },
      {
        id: 6,
        name: "Mergulho no Banco",
        muscles: "Tríceps, Peitoral Inferior",
        repeticoes: 12,
        series: 2,
        complete: false,
      },
    ],
  },
  {
    id: 2,
    name: "Treino de Costas e Bíceps",
    description: "Desenvolvimento completo da musculatura dorsal e bíceps",
    totalExercises: 6,
    totalSeries: 19,
    complete: true,
    exercises: [
      {
        id: 7,
        name: "Barra Fixa",
        muscles: "Grande Dorsal, Bíceps",
        repeticoes: 8,
        series: 4,
        complete: true,
      },
      {
        id: 8,
        name: "Remada Curvada com Barra",
        muscles: "Grande Dorsal, Trapézio",
        repeticoes: 10,
        series: 4,
        complete: true,
      },
      {
        id: 9,
        name: "Puxada Frontal",
        muscles: "Grande Dorsal",
        repeticoes: 12,
        series: 3,
        complete: true,
      },
      {
        id: 10,
        name: "Remada na Máquina",
        muscles: "Grande Dorsal, Trapézio",
        repeticoes: 12,
        series: 3,
        complete: true,
      },
      {
        id: 11,
        name: "Rosca Direta com Barra",
        muscles: "Bíceps",
        repeticoes: 10,
        series: 3,
        complete: true,
      },
      {
        id: 12,
        name: "Rosca Martelo com Halteres",
        muscles: "Bíceps, Braquial",
        repeticoes: 12,
        series: 2,
        complete: true,
      },
    ],
  },
  {
    id: 3,
    name: "Treino de Pernas Completo",
    description: "Treino intenso para quadríceps, posterior e glúteos",
    totalExercises: 5,
    totalSeries: 16,
    complete: false,
    exercises: [
      {
        id: 13,
        name: "Agachamento Livre",
        muscles: "Quadríceps, Glúteos, Posterior",
        repeticoes: 8,
        series: 4,
        complete: false,
      },
      {
        id: 14,
        name: "Leg Press 45°",
        muscles: "Quadríceps, Glúteos",
        repeticoes: 12,
        series: 4,
        complete: false,
      },
      {
        id: 15,
        name: "Mesa Flexora",
        muscles: "Posterior de Coxa",
        repeticoes: 12,
        series: 3,
        complete: false,
      },
      {
        id: 16,
        name: "Cadeira Extensora",
        muscles: "Quadríceps",
        repeticoes: 15,
        series: 3,
        complete: false,
      },
      {
        id: 17,
        name: "Panturrilha no Smith",
        muscles: "Panturrilha",
        repeticoes: 20,
        series: 2,
        complete: false,
      },
    ],
  },
  {
    id: 4,
    name: "Treino de Ombros e Abdômen",
    description: "Fortalecimento dos deltóides e core",
    totalExercises: 5,
    totalSeries: 15,
    complete: false,
    exercises: [
      {
        id: 18,
        name: "Desenvolvimento com Barra",
        muscles: "Deltóide, Trapézio",
        repeticoes: 10,
        series: 4,
        complete: false,
      },
      {
        id: 19,
        name: "Elevação Lateral com Halteres",
        muscles: "Deltóide Medial",
        repeticoes: 12,
        series: 3,
        complete: false,
      },
      {
        id: 20,
        name: "Elevação Frontal com Disco",
        muscles: "Deltóide Anterior",
        repeticoes: 12,
        series: 3,
        complete: false,
      },
      {
        id: 21,
        name: "Crucifixo Inverso na Polia",
        muscles: "Deltóide Posterior",
        repeticoes: 15,
        series: 3,
        complete: false,
      },
      {
        id: 22,
        name: "Abdominal na Prancha",
        muscles: "Abdômen, Core",
        repeticoes: 30,
        series: 2,
        complete: false,
      },
    ],
  },
];

// Mock diet data with Brazilian Portuguese food names
export const getMockDiets = (): DietaType[] => [
  {
    id: 1,
    name: "Dieta Balanceada - Ganho de Massa",
    alimentos: [
      {
        id: 1,
        name: "Peito de Frango Grelhado",
        calories: 165,
        fats: 3.6,
        carbs: 0,
        fibers: 0,
        sodium: 74,
        proteins: 31,
        acucars: {
          id: 1,
          acucarTotal: 0,
          acucarAdicionado: 0,
        },
        gorduras: {
          id: 1,
          gorduraTrans: 0,
          gordurasMonosaturadas: 1.2,
          gordurasPoliinsaturadas: 0.8,
          gordurasSaturadas: 1.0,
        },
      },
      {
        id: 2,
        name: "Arroz Integral",
        calories: 111,
        fats: 0.9,
        carbs: 23,
        fibers: 1.8,
        sodium: 5,
        proteins: 2.6,
        acucars: {
          id: 2,
          acucarTotal: 0.4,
          acucarAdicionado: 0,
        },
        gorduras: {
          id: 2,
          gorduraTrans: 0,
          gordurasMonosaturadas: 0.3,
          gordurasPoliinsaturadas: 0.3,
          gordurasSaturadas: 0.2,
        },
      },
      {
        id: 3,
        name: "Batata Doce Assada",
        calories: 90,
        fats: 0.1,
        carbs: 21,
        fibers: 3.3,
        sodium: 36,
        proteins: 2,
        acucars: {
          id: 3,
          acucarTotal: 6.5,
          acucarAdicionado: 0,
        },
        gorduras: {
          id: 3,
          gorduraTrans: 0,
          gordurasMonosaturadas: 0,
          gordurasPoliinsaturadas: 0,
          gordurasSaturadas: 0,
        },
      },
      {
        id: 4,
        name: "Brócolis Cozido",
        calories: 35,
        fats: 0.4,
        carbs: 7,
        fibers: 2.6,
        sodium: 33,
        proteins: 2.4,
        acucars: {
          id: 4,
          acucarTotal: 1.4,
          acucarAdicionado: 0,
        },
        gorduras: {
          id: 4,
          gorduraTrans: 0,
          gordurasMonosaturadas: 0,
          gordurasPoliinsaturadas: 0.2,
          gordurasSaturadas: 0.1,
        },
      },
      {
        id: 5,
        name: "Ovo Cozido",
        calories: 155,
        fats: 11,
        carbs: 1.1,
        fibers: 0,
        sodium: 124,
        proteins: 13,
        acucars: {
          id: 5,
          acucarTotal: 1.1,
          acucarAdicionado: 0,
        },
        gorduras: {
          id: 5,
          gorduraTrans: 0,
          gordurasMonosaturadas: 4.1,
          gordurasPoliinsaturadas: 1.4,
          gordurasSaturadas: 3.3,
        },
      },
    ],
  },
  {
    id: 2,
    name: "Dieta Low Carb",
    alimentos: [
      {
        id: 6,
        name: "Salmão Grelhado",
        calories: 206,
        fats: 12,
        carbs: 0,
        fibers: 0,
        sodium: 59,
        proteins: 22,
        acucars: {
          id: 6,
          acucarTotal: 0,
          acucarAdicionado: 0,
        },
        gorduras: {
          id: 6,
          gorduraTrans: 0,
          gordurasMonosaturadas: 4.5,
          gordurasPoliinsaturadas: 4.2,
          gordurasSaturadas: 2.5,
        },
      },
      {
        id: 7,
        name: "Abacate",
        calories: 160,
        fats: 15,
        carbs: 9,
        fibers: 7,
        sodium: 7,
        proteins: 2,
        acucars: {
          id: 7,
          acucarTotal: 0.7,
          acucarAdicionado: 0,
        },
        gorduras: {
          id: 7,
          gorduraTrans: 0,
          gordurasMonosaturadas: 10,
          gordurasPoliinsaturadas: 1.8,
          gordurasSaturadas: 2.1,
        },
      },
      {
        id: 8,
        name: "Azeite Extra Virgem (1 colher)",
        calories: 119,
        fats: 14,
        carbs: 0,
        fibers: 0,
        sodium: 0,
        proteins: 0,
        acucars: {
          id: 8,
          acucarTotal: 0,
          acucarAdicionado: 0,
        },
        gorduras: {
          id: 8,
          gorduraTrans: 0,
          gordurasMonosaturadas: 10,
          gordurasPoliinsaturadas: 1.4,
          gordurasSaturadas: 1.9,
        },
      },
    ],
  },
  {
    id: 3,
    name: "Dieta Vegetariana",
    alimentos: [
      {
        id: 9,
        name: "Feijão Preto Cozido",
        calories: 132,
        fats: 0.5,
        carbs: 24,
        fibers: 8.7,
        sodium: 2,
        proteins: 8.9,
        acucars: {
          id: 9,
          acucarTotal: 0.3,
          acucarAdicionado: 0,
        },
        gorduras: {
          id: 9,
          gorduraTrans: 0,
          gordurasMonosaturadas: 0.1,
          gordurasPoliinsaturadas: 0.2,
          gordurasSaturadas: 0.1,
        },
      },
      {
        id: 10,
        name: "Quinoa Cozida",
        calories: 120,
        fats: 1.9,
        carbs: 21,
        fibers: 2.8,
        sodium: 7,
        proteins: 4.4,
        acucars: {
          id: 10,
          acucarTotal: 0.9,
          acucarAdicionado: 0,
        },
        gorduras: {
          id: 10,
          gorduraTrans: 0,
          gordurasMonosaturadas: 0.5,
          gordurasPoliinsaturadas: 1.0,
          gordurasSaturadas: 0.2,
        },
      },
      {
        id: 11,
        name: "Tofu Grelhado",
        calories: 76,
        fats: 4.8,
        carbs: 1.9,
        fibers: 0.3,
        sodium: 7,
        proteins: 8,
        acucars: {
          id: 11,
          acucarTotal: 0.6,
          acucarAdicionado: 0,
        },
        gorduras: {
          id: 11,
          gorduraTrans: 0,
          gordurasMonosaturadas: 1.1,
          gordurasPoliinsaturadas: 2.7,
          gordurasSaturadas: 0.7,
        },
      },
    ],
  },
];
